import type { FeedCard } from './feedData';

export const enrichedFeedCards6: FeedCard[] = [

  // ===== STUDI KASUS TERPADU (10 cards) =====

  {
    id: 'enrich-skt-01',
    type: 'flashcard',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Kerangka IRAC',
    content: 'Jelaskan empat tahap kerangka IRAC yang digunakan dalam penulisan analisis kasus akuntan.',
    answer: 'IRAC terdiri dari: (1) Issue — identifikasi isu hukum/akuntansi yang relevan; (2) Rule — uraikan aturan, standar, atau prinsip yang berlaku (PSAK, UU, IESBA); (3) Application — terapkan aturan pada fakta kasus secara spesifik; (4) Conclusion — simpulkan posisi atau rekomendasi yang logis dan terukur. Setiap tahap harus terhubung erat agar analisis koheren.',
  },

  {
    id: 'enrich-skt-02',
    type: 'quiz',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Langkah Pertama IRAC',
    content: 'Dalam kerangka IRAC, langkah pertama yang harus dilakukan seorang kandidat saat membaca soal kasus adalah...',
    options: [
      'Langsung menuliskan kesimpulan agar efisien',
      'Mengidentifikasi seluruh isu yang relevan sebelum menganalisis',
      'Mencari standar akuntansi yang paling mungkin diterapkan',
      'Menghitung angka-angka keuangan yang tersedia',
    ],
    correctIndex: 1,
    explanation: 'Tahap pertama IRAC adalah Issue — kandidat harus mengidentifikasi semua isu yang relevan dari fakta kasus sebelum bergerak ke Rule. Melompati tahap ini berisiko mengabaikan isu penting yang dinilai.',
  },

  {
    id: 'enrich-skt-03',
    type: 'quiz',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'lanjutan',
    title: 'Identifikasi Isu Multi-Disiplin',
    content: 'Sebuah soal kasus menggambarkan perusahaan yang menerima uang muka pelanggan, memiliki aset sewa baru, dan direkturnya memegang saham di perusahaan audit. Berapa disiplin ilmu yang terlibat?',
    options: [
      'Satu disiplin: Akuntansi Keuangan',
      'Dua disiplin: Akuntansi Keuangan dan Audit',
      'Tiga disiplin: Akuntansi Keuangan, Sewa (PSAK 73), dan Etika/Audit',
      'Empat disiplin: Keuangan, Pajak, Audit, dan Hukum',
    ],
    correctIndex: 2,
    explanation: 'Uang muka pelanggan memunculkan isu PSAK 72 (pengakuan pendapatan), aset sewa memunculkan isu PSAK 73, dan direktur yang memegang saham di perusahaan audit menimbulkan isu ancaman independensi (IESBA/etika). Minimal tiga disiplin terlibat.',
  },

  {
    id: 'enrich-skt-04',
    type: 'quiz',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'lanjutan',
    title: 'Analisis Terintegrasi Lintas Ujian',
    content: 'Dalam kasus terpadu, penurunan nilai goodwill (PSAK 48) berdampak pada laporan keuangan. Dampak lintas disiplin mana yang paling kritis dibahas?',
    options: [
      'Hanya dampak pada laba rugi periode berjalan',
      'Dampak pada laba rugi, rasio keuangan untuk perjanjian utang (covenant), dan potensi isu going concern untuk auditor',
      'Hanya dampak pada neraca dan ekuitas pemegang saham',
      'Dampak pada pajak tangguhan saja',
    ],
    correctIndex: 1,
    explanation: 'Penurunan nilai goodwill memengaruhi laba rugi (biaya impairment), dapat melanggar covenant utang jika menurunkan rasio tertentu, dan jika material dapat memunculkan isu going concern yang harus dipertimbangkan auditor. Analisis terintegrasi mencakup semua dampak ini.',
  },

  {
    id: 'enrich-skt-05',
    type: 'flashcard',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Struktur Rekomendasi Terstruktur',
    content: 'Apa komponen kunci dari sebuah rekomendasi terstruktur dalam jawaban esai kasus CA?',
    answer: 'Rekomendasi terstruktur harus mencakup: (1) Pernyataan posisi yang jelas (setuju/tidak/kondisional); (2) Dasar standar — referensi eksplisit ke PSAK/IESBA/regulasi yang mendukung; (3) Penerapan pada fakta — hubungkan standar dengan kondisi spesifik klien; (4) Risiko atau konsekuensi jika rekomendasi diabaikan; (5) Tindakan konkret yang disarankan. Tanpa referensi standar, rekomendasi dianggap opini semata.',
  },

  {
    id: 'enrich-skt-06',
    type: 'quiz',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Manajemen Waktu Kasus',
    content: 'Ujian kasus CA mengalokasikan 180 menit untuk kasus senilai 100 poin dengan 5 pertanyaan bernilai 20 poin masing-masing. Berapa menit ideal per pertanyaan dan apa yang harus dilakukan jika satu pertanyaan melampaui alokasi?',
    options: [
      '30 menit per pertanyaan; terus mengerjakan hingga selesai sempurna',
      '36 menit per pertanyaan; pindah ke pertanyaan berikutnya meski belum selesai',
      '45 menit per pertanyaan; fokus pada pertanyaan pertama karena bernilai lebih',
      '20 menit per pertanyaan; sisakan 80 menit untuk revisi',
    ],
    correctIndex: 1,
    explanation: '180 menit dibagi 5 pertanyaan = 36 menit per pertanyaan. Disiplin waktu kritis: pindah ke soal berikutnya agar tidak kehilangan poin dari soal yang belum dijawab. Jawaban parsial tetap mendapat sebagian poin.',
  },

  {
    id: 'enrich-skt-07',
    type: 'quiz',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'lanjutan',
    title: 'Struktur Esai Profesional',
    content: 'Ciri utama esai profesional dalam ujian kasus CA yang membedakannya dari esai akademik biasa adalah...',
    options: [
      'Menggunakan kalimat panjang dan deskriptif untuk menunjukkan penguasaan materi',
      'Menggunakan heading, sub-heading, dan poin-poin ringkas dengan referensi standar yang eksplisit',
      'Menulis semua analisis dalam satu paragraf panjang agar mengalir',
      'Menghindari penyebutan standar akuntansi agar jawaban lebih fleksibel',
    ],
    correctIndex: 1,
    explanation: 'Esai profesional CA menggunakan struktur heading/sub-heading agar mudah dinilai, kalimat ringkas dan langsung, serta referensi standar (mis. "sesuai PSAK 72 paragraf 31") untuk mendukung argumen. Penguji menilai berdasarkan rubrik poin per poin.',
  },

  {
    id: 'enrich-skt-08',
    type: 'flashcard',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'lanjutan',
    title: 'Aplikasi Tahap Application dalam IRAC',
    content: 'Apa kesalahan paling umum kandidat dalam tahap Application (A) kerangka IRAC, dan bagaimana menghindarinya?',
    answer: 'Kesalahan paling umum adalah mengulang kembali aturan tanpa menghubungkannya dengan fakta spesifik kasus (parroting). Contoh kesalahan: "PSAK 72 mensyaratkan pengakuan pendapatan saat kewajiban pelaksanaan terpenuhi." Contoh yang benar: "Karena PT ABC belum menyerahkan barang kepada pelanggan per 31 Desember, kewajiban pelaksanaan belum terpenuhi, sehingga Rp500 juta uang muka belum dapat diakui sebagai pendapatan." Kunci: selalu sebutkan nama perusahaan, angka, dan tanggal dari kasus.',
  },

  {
    id: 'enrich-skt-09',
    type: 'quiz',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'lanjutan',
    title: 'Konflik Standar dalam Kasus',
    content: 'Dalam kasus terpadu, ditemukan bahwa perlakuan perpajakan atas suatu transaksi berbeda dengan perlakuan akuntansi (PSAK). Pendekatan yang tepat adalah...',
    options: [
      'Mengikuti perlakuan perpajakan karena lebih konservatif',
      'Mengabaikan perbedaan karena tidak material',
      'Mengakui perbedaan temporer dan membukukan pajak tangguhan sesuai PSAK 46',
      'Mengikuti PSAK dan mengabaikan kewajiban perpajakan',
    ],
    correctIndex: 2,
    explanation: 'Perbedaan antara perlakuan akuntansi (PSAK) dan perpajakan menciptakan beda temporer yang menimbulkan aset atau liabilitas pajak tangguhan sesuai PSAK 46. Laporan keuangan mengikuti PSAK, sedangkan SPT mengikuti peraturan perpajakan — keduanya tidak bisa diabaikan.',
  },

  {
    id: 'enrich-skt-10',
    type: 'flashcard',
    subject: 'Studi Kasus Terpadu',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Prioritas Isu dalam Kasus',
    content: 'Bagaimana cara menentukan urutan prioritas saat kasus terpadu mengandung banyak isu yang harus dianalisis?',
    answer: 'Prioritaskan isu berdasarkan: (1) Dampak keuangan terbesar — isu yang berpotensi menyebabkan salah saji material atau pelanggaran covenant utang dianalisis pertama; (2) Keterkaitan antar isu — isu yang saling memengaruhi dibahas bersama agar analisis koheren; (3) Risiko hukum atau regulasi — pelanggaran standar wajib lebih mendesak daripada pelanggaran aturan sukarela; (4) Poin rubrik — alokasikan waktu proporsional dengan bobot poin per isu dalam soal.',
  },

  // ===== ETIKA & TATA KELOLA (10 cards) =====

  {
    id: 'enrich-etk-01',
    type: 'flashcard',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'dasar',
    title: '5 Prinsip Fundamental IESBA',
    content: 'Sebutkan dan jelaskan singkat kelima prinsip fundamental IESBA yang wajib dipatuhi akuntan profesional.',
    answer: '(1) Integritas — jujur dan terus terang dalam semua hubungan profesional dan bisnis; (2) Objektivitas — tidak membiarkan bias, konflik kepentingan, atau pengaruh pihak lain mengesampingkan pertimbangan profesional; (3) Kompetensi dan Kehati-hatian Profesional — menjaga pengetahuan dan keterampilan pada level yang diperlukan; (4) Kerahasiaan — tidak mengungkapkan informasi klien tanpa otorisasi yang tepat kecuali ada kewajiban hukum; (5) Perilaku Profesional — mematuhi hukum dan regulasi yang relevan serta menghindari tindakan yang mendiskreditkan profesi.',
  },

  {
    id: 'enrich-etk-02',
    type: 'quiz',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Ancaman Self-Interest',
    content: 'Seorang auditor memiliki investasi saham signifikan di perusahaan klien auditnya. Jenis ancaman independensi apa yang timbul?',
    options: [
      'Ancaman advocacy',
      'Ancaman familiarity',
      'Ancaman self-interest',
      'Ancaman intimidation',
    ],
    correctIndex: 2,
    explanation: 'Ancaman self-interest timbul ketika auditor atau firma memiliki kepentingan keuangan dalam klien (mis. kepemilikan saham). Kepentingan ini dapat memengaruhi pertimbangan auditor secara tidak tepat demi menjaga nilai investasi. IESBA mengharuskan divestasi atau pengunduran diri dari penugasan.',
  },

  {
    id: 'enrich-etk-03',
    type: 'quiz',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Ancaman Self-Review',
    content: 'Firma akuntan publik yang sama menyusun laporan keuangan klien sekaligus mengauditnya. Ancaman independensi yang dominan adalah...',
    options: [
      'Ancaman self-interest karena mendapat dua fee',
      'Ancaman self-review karena auditor memeriksa hasil kerjanya sendiri',
      'Ancaman familiarity karena hubungan lama dengan klien',
      'Ancaman intimidation karena klien bisa mengancam mengganti auditor',
    ],
    correctIndex: 1,
    explanation: 'Ancaman self-review muncul ketika auditor mengevaluasi hasil pekerjaan yang sebelumnya dilakukan oleh dirinya sendiri atau firmanya. Mengaudit laporan keuangan yang disusun oleh tim yang sama di firma yang sama merupakan contoh klasik ancaman ini.',
  },

  {
    id: 'enrich-etk-04',
    type: 'quiz',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'lanjutan',
    title: 'Prinsip GCG TARIF',
    content: 'Akronim TARIF dalam prinsip GCG merujuk pada lima prinsip. Manakah pasangan yang TIDAK tepat?',
    options: [
      'T = Transparency (Keterbukaan)',
      'A = Accountability (Akuntabilitas)',
      'R = Responsibility (Pertanggungjawaban)',
      'I = Independence (Independensi) dan F = Fairness (Kewajaran) — keduanya benar',
    ],
    correctIndex: 3,
    explanation: 'Semua pasangan dalam TARIF benar: Transparency, Accountability, Responsibility, Independence, Fairness. Pertanyaan ini menguji apakah kandidat mengenali bahwa tidak ada pasangan yang salah dalam pilihan tersebut — pilihan D menyatakan kedua elemen terakhir benar, yang memang tepat.',
  },

  {
    id: 'enrich-etk-05',
    type: 'flashcard',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Dewan Komisaris vs Direksi (Two-Tier)',
    content: 'Jelaskan perbedaan peran Dewan Komisaris dan Direksi dalam sistem two-tier board Indonesia.',
    answer: 'Indonesia menganut sistem two-tier board: (1) Direksi — organ eksekutif yang bertanggung jawab menjalankan operasional perusahaan sehari-hari, membuat keputusan manajemen, dan merepresentasikan perusahaan secara hukum; (2) Dewan Komisaris — organ pengawas yang melakukan pengawasan atas kebijakan Direksi dan memberi nasihat. Dewan Komisaris tidak terlibat dalam manajemen operasional. Berbeda dengan sistem one-tier (Anglo-Saxon) yang menggabungkan keduanya dalam satu dewan (Board of Directors) dengan pembagian eksekutif dan non-eksekutif.',
  },

  {
    id: 'enrich-etk-06',
    type: 'quiz',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'lanjutan',
    title: 'Komite Audit POJK 55/2015',
    content: 'Berdasarkan POJK 55/2015, persyaratan keanggotaan Komite Audit perusahaan publik yang WAJIB dipenuhi adalah...',
    options: [
      'Minimal 2 anggota, semua berasal dari komisaris independen',
      'Minimal 3 anggota; diketuai komisaris independen; mayoritas anggota independen; minimal 1 anggota berlatar belakang akuntansi atau keuangan',
      'Minimal 5 anggota; semua harus berpendidikan S2 akuntansi',
      'Minimal 3 anggota; semua merupakan direktur independen perusahaan',
    ],
    correctIndex: 1,
    explanation: 'POJK 55/2015 mewajibkan Komite Audit minimal 3 anggota, diketuai oleh Komisaris Independen, mayoritas anggota bersifat independen dari perusahaan, dan minimal satu anggota memiliki keahlian di bidang akuntansi atau keuangan. Keanggotaan bukan dari Direksi.',
  },

  {
    id: 'enrich-etk-07',
    type: 'quiz',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Whistleblowing dan Prinsip Kerahasiaan',
    content: 'Seorang akuntan mengetahui adanya kecurangan material di perusahaan tempatnya bekerja. Berdasarkan kerangka IESBA, tindakan yang tepat adalah...',
    options: [
      'Diam karena prinsip kerahasiaan melarang pengungkapan informasi klien/perusahaan',
      'Langsung melapor ke media massa untuk transparansi publik',
      'Menyampaikan kekhawatiran melalui saluran internal dulu; jika gagal, pertimbangkan pelaporan ke otoritas berwenang sesuai regulasi',
      'Mengundurkan diri tanpa melaporkan apapun',
    ],
    correctIndex: 2,
    explanation: 'IESBA mengakui bahwa prinsip kerahasiaan tidak bersifat mutlak. Jika terdapat dugaan kecurangan, akuntan wajib menyampaikan kekhawatiran melalui jalur internal (atasan, komite audit). Jika jalur internal tidak efektif atau pelaku adalah manajemen puncak, pelaporan ke otoritas regulasi dapat dibenarkan. Laporan ke media tidak dianjurkan sebagai langkah pertama.',
  },

  {
    id: 'enrich-etk-08',
    type: 'flashcard',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'lanjutan',
    title: 'Ancaman Familiarity dan Intimidation',
    content: 'Berikan satu contoh konkret ancaman familiarity dan satu contoh ancaman intimidation dalam konteks audit, serta safeguard yang tepat.',
    answer: 'Familiarity: Auditor senior telah menangani klien yang sama selama 10 tahun sehingga terlalu percaya pada manajemen tanpa skeptisisme memadai. Safeguard: rotasi auditor kunci (partner rotation) sesuai regulasi. Intimidation: Klien mengancam akan mengganti KAP jika auditor tidak memodifikasi opininya terkait suatu pos material. Safeguard: mendokumentasikan ancaman tersebut, berkonsultasi dengan partner lain atau badan etika profesi, dan jika perlu mundur dari penugasan. Kedua ancaman ini dapat memengaruhi objektivitas dan integritas auditor.',
  },

  {
    id: 'enrich-etk-09',
    type: 'quiz',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'lanjutan',
    title: 'Prinsip Akuntabilitas GCG',
    content: 'Dalam konteks GCG, prinsip Accountability (Akuntabilitas) paling langsung diwujudkan melalui mekanisme apa?',
    options: [
      'Pembagian dividen yang merata kepada seluruh pemegang saham',
      'Pemisahan fungsi antara organ yang mengelola dan yang mengawasi perusahaan',
      'Pembukaan informasi harga saham secara real-time',
      'Pemberian insentif tinggi kepada direksi untuk meningkatkan kinerja',
    ],
    correctIndex: 1,
    explanation: 'Akuntabilitas mensyaratkan kejelasan fungsi, hak, kewajiban, dan wewenang masing-masing organ perusahaan. Mekanisme paling langsung adalah pemisahan fungsi antara pengelola (Direksi) dan pengawas (Dewan Komisaris), sehingga setiap pihak dapat dimintai pertanggungjawaban atas perannya masing-masing.',
  },

  {
    id: 'enrich-etk-10',
    type: 'flashcard',
    subject: 'Etika & Tata Kelola',
    level: 'ca',
    difficulty: 'menengah',
    title: 'Ancaman Advocacy dan Safeguard-nya',
    content: 'Apa itu ancaman advocacy dalam independensi auditor, berikan contoh, dan jelaskan safeguard yang tepat?',
    answer: 'Ancaman advocacy timbul ketika auditor mempromosikan posisi atau opini klien sedemikian rupa sehingga objektivitasnya terkompromi. Contoh: auditor bertindak sebagai negosiator atau juru bicara klien dalam transaksi, atau menjadi saksi ahli yang membela posisi klien di pengadilan. Safeguard: memisahkan personel yang memberikan jasa advokasi dari tim audit, atau menolak pemberian jasa tersebut jika ancaman tidak dapat dikurangi ke tingkat yang dapat diterima. Prinsip yang terancam adalah objektivitas dan independensi.',
  },

  // ===== PSAK & STANDAR AKUNTANSI (10 cards) =====

  {
    id: 'enrich-psak-01',
    type: 'flashcard',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'menengah',
    title: '5 Langkah PSAK 72',
    content: 'Jelaskan model 5-langkah pengakuan pendapatan menurut PSAK 72.',
    answer: '(1) Identifikasi kontrak dengan pelanggan — kontrak sah secara komersial dan hak serta kewajiban dapat diidentifikasi; (2) Identifikasi kewajiban pelaksanaan (performance obligation) — setiap janji untuk menyerahkan barang/jasa yang dapat dibedakan; (3) Tentukan harga transaksi — jumlah imbalan yang diharapkan diterima, termasuk pertimbangan variabel; (4) Alokasikan harga transaksi ke setiap kewajiban pelaksanaan berdasarkan harga jual mandiri (standalone selling price); (5) Akui pendapatan saat (atau sepanjang) kewajiban pelaksanaan terpenuhi.',
  },

  {
    id: 'enrich-psak-02',
    type: 'quiz',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'menengah',
    title: 'Pengakuan Pendapatan PSAK 72',
    content: 'PT Maju menerima uang muka Rp600 juta pada 1 Oktober untuk pengiriman barang pada 31 Januari tahun berikutnya. Pada 31 Desember, berapa pendapatan yang diakui?',
    options: [
      'Rp600 juta — pendapatan diakui saat kas diterima',
      'Rp300 juta — diakui secara proporsional selama periode kontrak',
      'Rp0 — pendapatan belum diakui karena barang belum diserahkan',
      'Rp150 juta — diakui berdasarkan persentase penyelesaian',
    ],
    correctIndex: 2,
    explanation: 'Berdasarkan PSAK 72 langkah ke-5, pendapatan diakui saat kewajiban pelaksanaan terpenuhi. Karena barang belum diserahkan pada 31 Desember, kewajiban pelaksanaan belum terpenuhi. Uang muka Rp600 juta dicatat sebagai liabilitas kontrak (contract liability/pendapatan diterima di muka).',
  },

  {
    id: 'enrich-psak-03',
    type: 'quiz',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'lanjutan',
    title: 'Kewajiban Pelaksanaan Terpisah',
    content: 'PT Teknologi menjual laptop seharga Rp15 juta yang mencakup perangkat keras dan garansi servis 2 tahun. Menurut PSAK 72, perlakuan yang tepat adalah...',
    options: [
      'Akui seluruh Rp15 juta sebagai pendapatan saat pengiriman laptop',
      'Tunda seluruh pendapatan hingga periode garansi berakhir',
      'Identifikasi dua kewajiban pelaksanaan terpisah; alokasikan harga transaksi berdasarkan harga jual mandiri masing-masing',
      'Akui Rp15 juta secara garis lurus selama 2 tahun',
    ],
    correctIndex: 2,
    explanation: 'Laptop dan garansi servis merupakan dua kewajiban pelaksanaan yang dapat dibedakan (distinct) — keduanya dapat berdiri sendiri dan pelanggan mendapat manfaat dari masing-masing secara terpisah. Harga transaksi Rp15 juta dialokasikan ke masing-masing berdasarkan standalone selling price, lalu diakui pada saat yang berbeda.',
  },

  {
    id: 'enrich-psak-04',
    type: 'flashcard',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'menengah',
    title: 'ROU Asset dan Liabilitas Sewa (PSAK 73)',
    content: 'Jelaskan konsep Right-of-Use (ROU) Asset dan Liabilitas Sewa dalam PSAK 73 serta bagaimana keduanya diukur awal.',
    answer: 'PSAK 73 mengharuskan penyewa (lessee) mengakui: (1) ROU Asset — hak untuk menggunakan aset sewaan selama masa sewa, diukur pada biaya perolehan yang mencakup nilai kini liabilitas sewa, pembayaran sewa yang dilakukan sebelum/pada tanggal dimulainya sewa, biaya langsung awal, dan estimasi biaya pembongkaran; (2) Liabilitas Sewa — kewajiban membayar sewa, diukur pada nilai kini pembayaran sewa yang belum dibayar menggunakan suku bunga implisit sewa atau suku bunga pinjaman inkremental penyewa. Setelah pengakuan awal, ROU Asset diamortisasi dan liabilitas sewa diukur dengan metode suku bunga efektif.',
  },

  {
    id: 'enrich-psak-05',
    type: 'quiz',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'menengah',
    title: 'Pengecualian PSAK 73',
    content: 'PSAK 73 memperbolehkan penyewa untuk tidak mengakui ROU Asset dan Liabilitas Sewa dalam kondisi...',
    options: [
      'Hanya jika sewa bersifat operasi dan bukan keuangan',
      'Jika masa sewa tidak lebih dari 12 bulan (sewa jangka pendek) ATAU jika aset sewaan bernilai rendah',
      'Jika nilai total sewa di bawah Rp1 miliar',
      'Jika sewa tidak memiliki opsi perpanjangan',
    ],
    correctIndex: 1,
    explanation: 'PSAK 73 memberikan dua pengecualian praktis: (1) sewa jangka pendek dengan masa sewa tidak lebih dari 12 bulan pada tanggal dimulainya sewa; dan (2) sewa aset bernilai rendah (low-value assets, misalnya komputer, tablet, furnitur kecil). Jika dikecualikan, pembayaran sewa diakui sebagai beban secara garis lurus.',
  },

  {
    id: 'enrich-psak-06',
    type: 'quiz',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'lanjutan',
    title: 'Komponen Laporan Keuangan PSAK 1',
    content: 'Berdasarkan PSAK 1 (Penyajian Laporan Keuangan), set lengkap laporan keuangan terdiri dari...',
    options: [
      'Neraca, Laporan Laba Rugi, dan Laporan Arus Kas',
      'Laporan Posisi Keuangan, Laporan Laba Rugi dan Penghasilan Komprehensif Lain, Laporan Perubahan Ekuitas, Laporan Arus Kas, dan Catatan atas Laporan Keuangan',
      'Laporan Laba Rugi, Laporan Arus Kas, dan Catatan atas Laporan Keuangan',
      'Neraca, Laporan Laba Rugi, Laporan Arus Kas, dan Laporan Auditor Independen',
    ],
    correctIndex: 1,
    explanation: 'PSAK 1 mensyaratkan set lengkap laporan keuangan terdiri dari: (1) Laporan Posisi Keuangan; (2) Laporan Laba Rugi dan Penghasilan Komprehensif Lain; (3) Laporan Perubahan Ekuitas; (4) Laporan Arus Kas; dan (5) Catatan atas Laporan Keuangan. Laporan Auditor Independen bukan bagian dari laporan keuangan itu sendiri.',
  },

  {
    id: 'enrich-psak-07',
    type: 'flashcard',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'menengah',
    title: 'Metode Arus Kas PSAK 2',
    content: 'Jelaskan perbedaan metode langsung dan metode tidak langsung dalam penyusunan Laporan Arus Kas (PSAK 2) untuk bagian aktivitas operasi.',
    answer: 'Metode Langsung: menyajikan penerimaan dan pengeluaran kas bruto dari aktivitas operasi secara terperinci (mis. kas diterima dari pelanggan, kas dibayar ke pemasok, kas dibayar untuk karyawan). Memberikan informasi lebih transparan tetapi memerlukan data yang lebih detail. Metode Tidak Langsung: dimulai dari laba bersih, kemudian disesuaikan dengan transaksi non-kas (penyusutan, amortisasi), perubahan modal kerja (piutang, persediaan, utang usaha), dan pos lain. Lebih umum digunakan karena lebih mudah disiapkan dari catatan akuntansi yang ada. PSAK 2 menganjurkan metode langsung tetapi memperbolehkan metode tidak langsung.',
  },

  {
    id: 'enrich-psak-08',
    type: 'quiz',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'lanjutan',
    title: 'Klasifikasi Arus Kas PSAK 2',
    content: 'PT Berkah membeli mesin produksi secara tunai Rp2 miliar dan membayar bunga pinjaman Rp150 juta. Dalam Laporan Arus Kas, kedua pos ini diklasifikasikan sebagai...',
    options: [
      'Keduanya aktivitas operasi',
      'Pembelian mesin: aktivitas investasi; bunga: boleh aktivitas operasi atau keuangan sesuai kebijakan konsisten',
      'Keduanya aktivitas investasi',
      'Pembelian mesin: aktivitas keuangan; bunga: aktivitas operasi',
    ],
    correctIndex: 1,
    explanation: 'PSAK 2: pembelian aset tetap (mesin) diklasifikasikan sebagai aktivitas investasi. Pembayaran bunga, menurut PSAK 2, boleh diklasifikasikan sebagai aktivitas operasi (karena masuk dalam penentuan laba) ATAU aktivitas keuangan (karena terkait perolehan pembiayaan), asalkan penerapannya konsisten antara periode.',
  },

  {
    id: 'enrich-psak-09',
    type: 'quiz',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'lanjutan',
    title: 'Konvergensi IFRS Indonesia',
    content: 'Pendekatan konvergensi PSAK terhadap IFRS yang diterapkan Indonesia adalah...',
    options: [
      'Adopsi penuh (full adoption) — PSAK identik dengan IFRS tanpa modifikasi apapun',
      'Adopsi sebagian — hanya standar yang dianggap relevan bagi Indonesia yang diadopsi',
      'Adopsi dengan modifikasi terbatas — PSAK berbasis IFRS dengan penyesuaian tertentu untuk kondisi Indonesia dan tanggal efektif yang mungkin berbeda',
      'Indonesia tidak mengadopsi IFRS dan menggunakan standar lokal sepenuhnya',
    ],
    correctIndex: 2,
    explanation: 'Indonesia menerapkan pendekatan adopsi dengan modifikasi terbatas: PSAK umumnya berbasis IFRS dengan beberapa penyesuaian untuk konteks hukum, perpajakan, atau kondisi pasar Indonesia, serta tanggal efektif yang bisa berbeda dari tanggal efektif IFRS internasional. IAI sebagai penyusun standar melakukan harmonisasi secara bertahap.',
  },

  {
    id: 'enrich-psak-10',
    type: 'flashcard',
    subject: 'PSAK & Standar Akuntansi',
    level: 'associate-ca',
    difficulty: 'menengah',
    title: 'Penghasilan Komprehensif Lain (OCI)',
    content: 'Apa yang dimaksud dengan Penghasilan Komprehensif Lain (Other Comprehensive Income/OCI) dalam PSAK 1, dan sebutkan minimal tiga contoh itemnya?',
    answer: 'OCI adalah item penghasilan dan beban yang tidak diakui dalam laba rugi periode berjalan karena PSAK lain melarang atau mengizinkan pengklasifikasiannya di luar laba rugi. Tiga contoh utama: (1) Surplus revaluasi aset tetap dan aset takberwujud (PSAK 16/PSAK 19); (2) Pengukuran kembali (remeasurement) kewajiban imbalan pasti seperti program pensiun (PSAK 24); (3) Selisih kurs dari penjabaran laporan keuangan operasi luar negeri (PSAK 10). OCI disajikan dalam Laporan Laba Rugi dan Penghasilan Komprehensif Lain sebagai bagian terpisah setelah laba rugi.',
  },
];
