import type { FeedCard } from './feedData';

export const enrichedFeedCards7: FeedCard[] = [
  // --- QUIZ CARDS (10) ---
  {
    id: 'enrich-su-1',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'dasar',
    title: 'Alokasi Waktu Per Soal',
    content: 'Dalam ujian berdurasi 120 menit dengan 60 soal pilihan ganda, berapa menit ideal yang dialokasikan per soal agar masih ada waktu review?',
    options: [
      '3 menit per soal, sisakan 30 menit untuk review',
      '2 menit per soal, sisakan 0 menit untuk review',
      '1,5 menit per soal, sisakan 30 menit untuk review',
      '1 menit per soal, sisakan 60 menit untuk review',
    ],
    correctIndex: 2,
    explanation: 'Dengan 1,5 menit per soal, 60 soal membutuhkan 90 menit, menyisakan 30 menit untuk review dan soal yang dilewati. Ini adalah alokasi yang seimbang antara kecepatan mengerjakan dan waktu koreksi.',
  },
  {
    id: 'enrich-su-2',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'dasar',
    title: 'Teknik Skipping yang Tepat',
    content: 'Kapan teknik skipping (melewati soal) paling tepat diterapkan saat mengerjakan ujian?',
    options: [
      'Ketika soal terasa sedikit sulit meskipun masih bisa dikerjakan',
      'Ketika soal membutuhkan waktu lama dan jawabannya tidak segera terpikirkan',
      'Ketika soal berasal dari topik yang tidak disukai',
      'Ketika nomor soal ganjil',
    ],
    correctIndex: 1,
    explanation: 'Skipping paling efektif ketika sebuah soal memakan waktu lebih dari batas ideal dan jawaban tidak segera muncul. Tandai soal tersebut, lanjutkan ke soal berikutnya, dan kembali di akhir. Tujuannya adalah memaksimalkan jumlah soal yang berhasil dijawab.',
  },
  {
    id: 'enrich-su-3',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'menengah',
    title: 'Identifikasi Kata Kunci Soal',
    content: 'Saat membaca soal pilihan ganda, kata mana yang paling kritis untuk digarisbawahi guna menghindari kesalahan interpretasi?',
    options: [
      'Kata benda yang menjadi subjek soal',
      'Kata negatif seperti "kecuali", "bukan", dan "tidak"',
      'Kata kerja yang menjelaskan tindakan',
      'Nama tokoh atau perusahaan dalam soal',
    ],
    correctIndex: 1,
    explanation: 'Kata negatif ("kecuali", "bukan", "tidak benar") paling sering menjadi jebakan karena mudah terlewat saat membaca cepat. Menggarisbawahi kata-kata ini secara fisik atau mental mencegah kesalahan yang tidak perlu, terutama saat kondisi lelah atau stres.',
  },
  {
    id: 'enrich-su-4',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'menengah',
    title: 'Strategi Eliminasi Jawaban',
    content: 'Dengan menggunakan strategi eliminasi dan berhasil menyingkirkan dua opsi yang jelas salah dari empat pilihan, berapa probabilitas menjawab benar?',
    options: [
      '25%',
      '33%',
      '50%',
      '75%',
    ],
    correctIndex: 2,
    explanation: 'Mengeliminasi dua dari empat opsi meningkatkan peluang dari 25% (1/4) menjadi 50% (1/2). Bahkan mengeliminasi satu opsi saja sudah meningkatkan peluang ke 33%. Strategi ini sangat berharga ketika tidak yakin 100% dengan jawaban.',
  },
  {
    id: 'enrich-su-5',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'menengah',
    title: 'Teknik IRAC untuk Esai',
    content: 'Dalam teknik IRAC untuk soal esai akuntansi, apa yang dimaksud dengan komponen "A" (Analysis)?',
    options: [
      'Menulis asumsi yang digunakan dalam perhitungan',
      'Menerapkan aturan atau standar yang relevan pada fakta kasus yang diberikan',
      'Menjawab pertanyaan dengan singkat di awal paragraf',
      'Mengidentifikasi akun-akun yang terpengaruh',
    ],
    correctIndex: 1,
    explanation: 'Dalam IRAC: Issue (identifikasi masalah), Rule (sebutkan aturan/standar relevan), Analysis (terapkan aturan pada fakta kasus), Conclusion (simpulkan jawaban). Komponen Analysis adalah inti dari esai karena menunjukkan kemampuan penerapan pengetahuan, bukan sekadar hafalan.',
  },
  {
    id: 'enrich-su-6',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'lanjutan',
    title: 'Prioritas Belajar Berdasarkan Bobot',
    content: 'Jika distribusi ujian adalah: Topik A (40%), Topik B (35%), Topik C (15%), Topik D (10%), dan waktu belajar terbatas, pendekatan mana yang paling optimal?',
    options: [
      'Belajar keempat topik secara merata agar semua dikuasai',
      'Fokus pada Topik C dan D karena lebih mudah dikuasai',
      'Kuasai Topik A dan B terlebih dahulu karena mencakup 75% soal',
      'Prioritaskan Topik D karena bobotnya kecil sehingga lebih mudah diselesaikan',
    ],
    correctIndex: 2,
    explanation: 'Dengan waktu terbatas, memaksimalkan penguasaan topik berbobot tinggi memberikan return terbesar. Topik A dan B mencakup 75% nilai ujian. Setelah menguasai keduanya, alokasikan sisa waktu untuk Topik C dan D. Ini adalah penerapan prinsip Pareto dalam belajar.',
  },
  {
    id: 'enrich-su-7',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'dasar',
    title: 'Manfaat Latihan Soal Tahun Lalu',
    content: 'Apa manfaat utama mengerjakan soal-soal ujian tahun-tahun sebelumnya?',
    options: [
      'Memastikan soal yang sama akan keluar kembali di ujian mendatang',
      'Membiasakan diri dengan format, tingkat kesulitan, dan pola soal yang sering muncul',
      'Mengurangi kebutuhan untuk mempelajari materi baru',
      'Mendapatkan nilai sempurna tanpa perlu memahami konsep',
    ],
    correctIndex: 1,
    explanation: 'Soal tahun lalu membantu mengenali format ujian, distribusi topik, tingkat kesulitan rata-rata, dan jenis pertanyaan yang sering muncul. Ini melatih kecepatan dan strategi pengerjaan, bukan untuk menghafal jawaban, karena soal yang persis sama jarang berulang.',
  },
  {
    id: 'enrich-su-8',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'menengah',
    title: 'Teknik Review Akhir Sebelum Submit',
    content: 'Saat melakukan review akhir jawaban sebelum submit, kapan sebaiknya mengubah jawaban yang sudah dipilih?',
    options: [
      'Selalu ubah jika ada keraguan, karena intuisi pertama sering salah',
      'Jangan pernah ubah karena jawaban pertama selalu paling benar',
      'Ubah hanya jika ada alasan logis yang jelas, bukan sekadar keraguan tanpa dasar',
      'Ubah semua jawaban yang pengerjaannya memakan waktu lama',
    ],
    correctIndex: 2,
    explanation: 'Penelitian menunjukkan bahwa mengubah jawaban tanpa alasan yang kuat sering merugikan. Ubah jawaban hanya ketika ada alasan konkret: menemukan informasi baru di soal lain, menyadari salah baca soal, atau ingat fakta spesifik yang relevan. Keraguan semata bukan alasan yang cukup.',
  },
  {
    id: 'enrich-su-9',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'menengah',
    title: 'Spaced Repetition vs Massed Practice',
    content: 'Mengapa spaced repetition (pengulangan terjadwal) lebih efektif dibandingkan massed practice (belajar sekaligus dalam satu sesi panjang)?',
    options: [
      'Karena spaced repetition membutuhkan lebih sedikit total jam belajar',
      'Karena pengulangan dengan jeda memaksa otak melakukan retrieval aktif yang memperkuat memori jangka panjang',
      'Karena massed practice menyebabkan kelelahan fisik yang lebih cepat',
      'Karena spaced repetition lebih mudah dijadwalkan',
    ],
    correctIndex: 1,
    explanation: 'Setiap kali otak harus mengingat kembali (retrieve) informasi setelah jeda, proses ini memperkuat jalur memori. Massed practice menciptakan ilusi penguasaan karena informasi masih segar di memori jangka pendek, tetapi cepat dilupakan. Spaced repetition memanfaatkan "spacing effect" untuk retensi jangka panjang.',
  },
  {
    id: 'enrich-su-10',
    type: 'quiz',
    subject: 'Strategi Ujian',
    difficulty: 'dasar',
    title: 'Persiapan H-1 Ujian',
    content: 'Kegiatan mana yang paling tepat dilakukan pada H-1 (malam sebelum) ujian?',
    options: [
      'Belajar materi baru sebanyak mungkin untuk memaksimalkan pengetahuan',
      'Begadang mengulang semua catatan dari awal hingga akhir',
      'Review ringkasan materi secara ringan, tidur cukup 7-8 jam, dan siapkan dokumen ujian',
      'Mengerjakan seluruh paket soal simulasi untuk terakhir kalinya',
    ],
    correctIndex: 2,
    explanation: 'H-1 bukan waktu untuk belajar intensif. Otak membutuhkan istirahat untuk mengkonsolidasikan memori. Review ringan membantu mengaktifkan pengetahuan tanpa menambah beban kognitif. Tidur cukup terbukti secara ilmiah meningkatkan kemampuan recall dan pengambilan keputusan saat ujian.',
  },

  // --- FLASHCARD CARDS (6) ---
  {
    id: 'enrich-su-11',
    type: 'flashcard',
    subject: 'Strategi Ujian',
    difficulty: 'dasar',
    title: 'Definisi Teknik Skipping',
    content: 'Apa yang dimaksud dengan teknik skipping dalam konteks ujian, dan bagaimana cara menandai soal yang dilewati?',
    answer: 'Teknik skipping adalah strategi melewati soal yang membutuhkan waktu terlalu lama dan kembali mengerjakannya di akhir. Caranya: tandai nomor soal dengan simbol khusus (misal: tanda bintang atau lingkaran) pada lembar jawaban atau soal, lanjutkan ke soal berikutnya, dan kerjakan soal yang dilewati setelah semua soal lain selesai atau di sesi review.',
  },
  {
    id: 'enrich-su-12',
    type: 'flashcard',
    subject: 'Strategi Ujian',
    difficulty: 'menengah',
    title: 'Empat Langkah IRAC',
    content: 'Sebutkan dan jelaskan secara singkat keempat komponen teknik IRAC untuk menjawab soal esai!',
    answer: 'I - Issue: Identifikasi masalah hukum/akuntansi yang harus dijawab. R - Rule: Sebutkan aturan, standar (PSAK, IFRS), atau prinsip yang relevan. A - Analysis: Terapkan aturan tersebut pada fakta-fakta spesifik yang diberikan dalam soal. C - Conclusion: Simpulkan jawaban secara tegas berdasarkan analisis yang telah dilakukan.',
  },
  {
    id: 'enrich-su-13',
    type: 'flashcard',
    subject: 'Strategi Ujian',
    difficulty: 'menengah',
    title: 'Active Recall vs Rereading',
    content: 'Apa perbedaan antara active recall dan rereading (membaca ulang), dan mana yang lebih efektif untuk belajar?',
    answer: 'Rereading adalah membaca ulang materi secara pasif. Active recall adalah menutup materi dan mencoba mengingat kembali informasinya secara aktif (misal: menjawab pertanyaan tanpa melihat catatan, membuat flashcard). Active recall jauh lebih efektif karena proses retrieval memperkuat jejak memori, sedangkan rereading hanya menciptakan keakraban (familiarity) yang tidak sama dengan penguasaan (mastery).',
  },
  {
    id: 'enrich-su-14',
    type: 'flashcard',
    subject: 'Strategi Ujian',
    difficulty: 'dasar',
    title: 'Tiga Teknik Eliminasi Distractor',
    content: 'Sebutkan tiga cara untuk mengidentifikasi dan mengeliminasi pilihan jawaban yang salah (distractor) dalam soal pilihan ganda!',
    answer: '1. Eliminasi ekstrem: opsi yang menggunakan kata absolut ("selalu", "tidak pernah") biasanya salah karena jarang ada pernyataan yang benar secara mutlak. 2. Eliminasi kontradiksi: jika dua opsi saling bertentangan, salah satu kemungkinan benar; eliminasi opsi lainnya. 3. Eliminasi ketidaksesuaian: opsi yang tidak relevan dengan topik pertanyaan atau menggunakan terminologi yang salah konteks dapat langsung dieliminasi.',
  },
  {
    id: 'enrich-su-15',
    type: 'flashcard',
    subject: 'Strategi Ujian',
    difficulty: 'lanjutan',
    title: 'Manajemen Stres Kognitif Saat Ujian',
    content: 'Sebutkan dua teknik manajemen stres yang dapat diterapkan langsung saat menghadapi soal sulit di tengah ujian!',
    answer: '1. Pernapasan 4-7-8: tarik napas 4 detik, tahan 7 detik, hembuskan 8 detik. Teknik ini mengaktifkan sistem saraf parasimpatik dan menurunkan kortisol secara cepat. 2. Cognitive reframing: alihkan pikiran dari "Saya tidak tahu ini" menjadi "Saya lewati dulu dan kembali nanti". Ini mencegah panic spiral yang membuang waktu dan menghambat pengambilan keputusan.',
  },
  {
    id: 'enrich-su-16',
    type: 'flashcard',
    subject: 'Strategi Ujian',
    difficulty: 'menengah',
    title: 'Simulasi Ujian: Kondisi yang Harus Direplikasi',
    content: 'Apa saja kondisi yang harus direplikasi saat melakukan simulasi ujian agar latihan menjadi efektif?',
    answer: 'Kondisi yang harus direplikasi: (1) durasi waktu yang sama persis dengan ujian nyata, (2) lingkungan tenang tanpa gangguan (matikan notifikasi), (3) tidak membuka catatan selama pengerjaan, (4) menggunakan format soal yang sama, (5) mengerjakan di waktu yang sama dengan jadwal ujian asli untuk melatih ritme kognitif. Tujuannya adalah menciptakan memori prosedural yang akan aktif secara otomatis saat ujian.',
  },

  // --- TIP CARDS (4) ---
  {
    id: 'enrich-su-17',
    type: 'tip',
    subject: 'Strategi Ujian',
    difficulty: 'dasar',
    title: 'Aturan Dua Menit untuk Soal Sulit',
    content: 'Tetapkan batas waktu dua menit per soal saat mengerjakan ujian. Jika setelah dua menit Anda belum menemukan jawaban yang meyakinkan, segera tandai soal tersebut dan lanjut ke soal berikutnya. Jangan biarkan satu soal sulit memakan waktu yang seharusnya digunakan untuk menjawab beberapa soal mudah. Di akhir sesi, kembali ke soal yang ditandai dengan pikiran lebih segar. Konsistensi dalam menerapkan batas waktu ini adalah kunci manajemen waktu yang efektif.',
    keyTakeaway: 'Satu soal sulit tidak boleh mengorbankan waktu untuk banyak soal mudah yang bisa dijawab.',
  },
  {
    id: 'enrich-su-18',
    type: 'tip',
    subject: 'Strategi Ujian',
    difficulty: 'menengah',
    title: 'Metode Feynman untuk Review Materi',
    content: 'Gunakan metode Feynman sebagai teknik review: ambil selembar kertas kosong dan coba jelaskan konsep yang baru dipelajari seolah-olah Anda mengajari orang yang tidak memiliki latar belakang akuntansi. Bagian mana yang tidak bisa dijelaskan dengan sederhana adalah bagian yang belum benar-benar dipahami. Kembali ke sumber materi hanya untuk bagian tersebut, lalu ulangi proses penjelasan. Metode ini jauh lebih efektif daripada membaca ulang catatan secara pasif.',
    keyTakeaway: 'Jika tidak bisa menjelaskan suatu konsep dengan bahasa sederhana, berarti pemahaman Anda belum cukup kuat untuk ujian.',
  },
  {
    id: 'enrich-su-19',
    type: 'tip',
    subject: 'Strategi Ujian',
    difficulty: 'dasar',
    title: 'Checklist Persiapan H-1 Ujian',
    content: 'Pada malam sebelum ujian, lakukan checklist berikut: (1) Siapkan semua dokumen yang diperlukan (kartu identitas, kartu peserta ujian, alat tulis) dan letakkan di tempat yang mudah diambil. (2) Tentukan rute dan waktu keberangkatan agar tiba 30 menit sebelum ujian dimulai. (3) Lakukan review ringan selama maksimal 60 menit, fokus pada ringkasan dan formula kunci saja. (4) Hindari mempelajari materi baru sama sekali. (5) Tidur minimal 7 jam. Persiapan logistik yang baik menghilangkan sumber stres non-akademik pada hari ujian.',
    keyTakeaway: 'H-1 adalah tentang persiapan fisik dan logistik, bukan belajar materi baru.',
  },
  {
    id: 'enrich-su-20',
    type: 'tip',
    subject: 'Strategi Ujian',
    difficulty: 'lanjutan',
    title: 'Membangun Jadwal Belajar Berbasis Bobot Ujian',
    content: 'Sebelum memulai sesi belajar, unduh silabus resmi ujian dan catat persentase bobot setiap topik. Buat jadwal belajar di mana alokasi waktu per topik proporsional dengan bobotnya di ujian. Misalnya, topik berbobot 40% mendapat 40% dari total jam belajar Anda. Dalam setiap sesi topik, gunakan 60% waktu untuk memahami konsep dan 40% waktu untuk latihan soal bertopik tersebut. Evaluasi kemajuan mingguan dan redistribusi waktu jika ada topik yang lebih lambat dikuasai dari rencana.',
    keyTakeaway: 'Alokasi waktu belajar harus mencerminkan bobot topik di ujian, bukan preferensi pribadi atau tingkat kesulitan yang dirasakan.',
  },
];
